CREATE TABLE IF NOT EXISTS shipping_info (
  id INT NOT NULL DEFAULT 1,
  image_url VARCHAR(500) NULL,
  title VARCHAR(200) NULL,
  description TEXT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

INSERT IGNORE INTO shipping_info (id) VALUES (1);
