CREATE TABLE IF NOT EXISTS hero_images (
  id         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  image_url  VARCHAR(500) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
